### ISSUE TITLE
unable to start varnish , see logs 

### ISSUE THREAD

**Issue by javaspects** [ewolff/SCS-ESI#2]
that's what I always get, when trying to start the demo....(logs of container) : 

vagrant@vagrant:/repos/ztestdir/SCS-ESI/docker$ docker logs scsesi_varnish_1
Can't open VSM file (Cannot open /var/lib/varnish/2a32d6799caa/_.vsm: No such file or directory
)

I imagine that in *default.vcl* I have to replace the >host< by 127.0.0.1 if I run it in my vagrant-box ?

**Comment by ewolff** [comment]
I just tried to run the demo on a freshly installed system and had no problems. It works and I don't get the log entry you are seeing.

The  host entries in `default.vcl` are host names that are resolved by Docker Compose. I.e. `order` and `common`are correct.

Actually I am not sure what you are trying to do as there is no Vagrant in this demo. However, the demo should just work on a system whether it is Linux or anything else.

**Comment by javaspects** [comment]
Hello Eberhard,
thank you for the quick answer. I installed Vagrant on my Windows machine.
Therein I installed docker (compose) and, well, I faced the issue...
I'll try on my colleagues machine to verify if it's reproduceable...

Best regards,
Esteban

Eberhard Wolff <notifications@github.com> schrieb am Fr., 12. Okt. 2018,
20:18:

**Comment by ewolff** [comment]
I am not sure what is going on here. As I said I tried it on a different machine with a fresh Docker installation and wasn't able to reproduce it. Maybe if you send the full log and also the log for the build of the container, things could be clearer.

What you can try:

- Remove the existing container with `docker rm scsesi_vagrant_1` . It should be rebuild from the image then.

- Remove the exisiting image with `docker rmi scsesi_vagrant`. You can rebuild it with `docker-compose build`.

- Use [Docker Community Edition](https://www.docker.com/community-edition/) instead of Docker on a Linux VM. For older Windows versions there is also the [Docker Toolbox](https://docs.docker.com/toolbox/toolbox_install_windows/).

- Using Docker Community Edition or Docker Toolkit you can also use Docker Machine to setup a VM with Docker, see https://github.com/ewolff/microservice/blob/master/docker/README.md .

**Comment by javaspects** [comment]
Hallo Eberhard, 
ich habe das Problem gelöst, d.h. das Problem lag zwischen Stuhl und Monitor :-)

I had Proxy, network problems.
Thank you very much !
Esteban.

**Comment by ewolff** [comment]
Excellent - glad it works for you! 👍🙂
